---
version: "3.2"
services:
  app80:
    build:
      context: .
      args:
        PHP_VERSION: "8.0"
    environment:
        PHP_IDE_CONFIG: 'serverName=brickrouge'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
  app82:
    build:
      context: .
      args:
        PHP_VERSION: "8.2"
    environment:
        PHP_IDE_CONFIG: 'serverName=brickrouge'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
